version: "3.7"

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "16686:16686" # web ui
      - "14268"
      - "14250"

  # Collector
  otel-collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55679:55679" # zpages extension
    depends_on:
      - jaeger

  minio:
    image: minio/minio
    entrypoint: [""]
    command:
      - "sh"
      - "-c"
      - "mkdir -p /data/saferplace && minio server --quiet /saferplace --console-address :9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=saferplace
      - MINIO_ROOT_PASSWORD=supersecret

  surrealdb:
    entrypoint: 
      - /surreal 
      - start 
      - --user
      - saferplace
      - --pass
      - supersecret
    image: surrealdb/surrealdb:1.0.0
    ports:
      - 8000:8000
    environment:
      # Why not working???
      - SURREAL_TRACING_TRACER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    depends_on:
      - otel-collector
