version: "3.7"

services:
  minio:
    image: minio/minio
    entrypoint: [""]
    command:
      - "sh"
      - "-c"
      - "mkdir -p /data/saferplace && minio server --quiet /saferplace --console-address :9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=saferplace
      - MINIO_ROOT_PASSWORD=supersecret
