# Workflow used as Continous Integration every time we have a PR.
name: CI

on:
  # Only build when pushed to main
  push:
    branches:
    - main
  # Build all pull requests
  pull_request:

env:
  GOPRIVATE: github.com/saferplace

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Lint with golangci-lint
      uses: golangci/golangci-lint-action@v3

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Set up Go
      uses: actions/setup-go@v4
    - name: Build
      run: go build ./...
    - name: Run Unit Tests
      run: go test ./... > test.json
    - name: Annotate Tests
      uses: guyarb/golang-test-annotations@v0.5.1
      with:
        test-results: test.json