# Workflow used as Continous Integration every time we have a PR.
name: Go

on:
  # Only build when pushed to main
  push:
    branches:
      - main
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
  # Build all pull requests
  pull_request:
    branches:
      - main
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - run: git config --global url.https://${{ secrets.GH_GO_MOD_TOKEN }}@github.com/.insteadOf https://github.com/
    - name: Lint with golangci-lint
      uses: golangci/golangci-lint-action@v3

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Set up Go
      uses: actions/setup-go@v4
    - run: git config --global url.https://${{ secrets.GH_GO_MOD_TOKEN }}@github.com/.insteadOf https://github.com/
    - name: Build
      run: go build ./...
    - name: Run Unit Tests
      run: go test ./... -json > test.json
    - name: Annotate Tests
      uses: guyarb/golang-test-annotations@v0.7.0
      with:
        test-results: test.json